compile:
	gcc -ggdb -mpreferred-stack-boundary=3 -fno-stack-protector -z execstack -o ShellCode ShellCode.c

compile32:
	gcc -ggdb -m32 -mpreferred-stack-boundary=3 -fno-stack-protector -z execstack -o ShellCode_32 ShellCode.c
