compile:
	gcc -ggdb -m32 -mpreferred-stack-boundary=3 -fno-stack-protector -z execstack -o format format-string.c

compile2:
	gcc -ggdb -m32 -mpreferred-stack-boundary=3 -fno-stack-protector -z execstack -o format2 format-string2.c
